# JDBC properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  sql:
    init:
      platform: postgres
#SWAGGER
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    #SECURITY
    import: secrets.yml

server:
  port: 2137





